import {
  about as aboutStatic,
  bring as bringStatic,
  breakSequence,
  contactAside,
  process as processStatic,
  processIncludes,
  projectTypes,
  stackGroups as stackGroupsStatic,
  stats as statsStatic,
} from "../content";
import { footerLinks, navCta, navLinks, site as siteStatic, socials as socialsStatic } from "../data";
import type { LandingContent } from "./types";

export const defaultLanding: LandingContent = {
  site: {
    name: siteStatic.name,
    firstName: siteStatic.firstName,
    email: siteStatic.email,
    phone: siteStatic.phone,
    location: siteStatic.location,
    roleTitle: siteStatic.roleTitle,
    resumeUrl: siteStatic.resumeUrl,
    resumeFileName: siteStatic.resumeFileName,
  },
  nav: {
    links: navLinks.map((l) => ({ ...l })),
    cta: { ...navCta },
  },
  footer: {
    links: footerLinks.map((l) => ({ ...l })),
  },
  socials: socialsStatic.map((s) => ({ ...s })),
  hero: {
    portraitSrc: "/v2/hero-portrait-full.png",
    handLines: [`Hi, I'm ${siteStatic.firstName}.`, "Shipping interfaces that", "hold up in production."],
    proofText: "7+ years shipping products",
    badgeText: "Available for work",
    rating: "4.9",
    titleLine1: "Building Production-Grade",
    titleAccent: "Frontend Products.",
    lead: "Build the skills companies expect from strong frontend engineers — from React architecture and performance to scalable, production-ready systems.",
    features: ["Architecture-first", "Project-driven builds", "AI-assisted workflows"],
    primaryCta: { label: "Let's work together", href: "#contact" },
    secondaryCta: { label: "View selected work", href: "#works" },
    trustItems: ["Open to new opportunities", "Available for freelance", "Open to collaborations"],
    avatars: ["/v2/avatars/a1.jpg", "/v2/avatars/a2.jpg", "/v2/avatars/a3.jpg", "/v2/avatars/a4.jpg"],
  },
  stats: statsStatic.map((x) => ({ ...x })),
  stackGroups: stackGroupsStatic.map((g) => ({ title: g.title, items: [...g.items] })),
  gap: {
    tagline: "01 / The Engineering Gap",
    dim: "Code is cheap.",
    bright: "Judgment is",
    brightAccent: "valuable.",
    body: "Deciding what to build, whether it's correct, and how it fits the product is the skill that matters now.",
    bodyMutedBefore: "AI changed the job, not the craft. When AI writes the code,",
    bodyMutedUnderline: "my job is to verify it",
    bodyMutedAfter: ", test it, and make sure it holds up in production.",
    handLines: ["this is what I bring", "to every build"],
    items: [
      { label: "Architecture", stack: "React · Next.js · component systems" },
      { label: "Product thinking", stack: "users · constraints · trade-offs" },
      { label: "Performance", stack: "Core Web Vitals · bundles · caching" },
      { label: "Accessibility", stack: "WCAG · semantics · keyboard" },
      { label: "Testing", stack: "Unit · integration · E2E" },
      { label: "Delivery", stack: "CI/CD · reviews · observability" },
    ],
  },
  bring: {
    tagline: "02 / What I bring",
    dim: "What I bring",
    bright: "to every",
    brightAccent: "build.",
    lead: "Four things every team gets, regardless of stack or project size.",
    items: bringStatic.map((b) => ({ ...b })),
  },
  stakes: {
    tagline: "03 / What's at stake",
    dim: "Every interface breaks.",
    bright: "Someone has to",
    brightAccent: "know why.",
    lead: "I don't just build interfaces that look good in a screenshot. I build interfaces that survive real users, real devices and real production environments.",
    sequence: [...breakSequence],
    leadSmall: "AI gives you a probable fix, not one proven for your users. Knowing the difference is engineering.",
    closingDim: "AI gives you a possible fix.",
    closingBrightBefore: "Knowing if it's the fix is",
    closingBrightAccent: "engineering.",
  },
  showcase: {
    tagline: "04 / Selected work",
    badge: "Available for new projects",
    titleBefore: "",
    titleAccent: "30+",
    titleAfter: "products shipped.",
    lead: "From early-stage startups to production systems used by real teams. Six of them, with the role I played, the stack and the outcome.",
    leadNote: "Open a project for the details.",
  },
  experience: {
    tagline: "05 / Experience",
    dim: "Seven years of shipping.",
    bright: "Four teams, real",
    brightAccent: "products.",
    aside:
      "Frontend since 2018 — from static templates to CRMs, mobile apps and AI-assisted tools. Every role shipped to real users.",
    resumeLabel: "Download resume",
  },
  process: {
    tagline: "06 / Process",
    dim: "How I work",
    bright: "with",
    brightAccent: "teams.",
    lead: "Four steps, repeated at every scale — from a single feature to a product rebuild. You see progress every week and know what is coming next.",
    steps: processStatic.map((p) => ({ ...p })),
    includes: [...processIncludes],
  },
  about: {
    tagline: "07 / About",
    heading: aboutStatic.heading,
    statement: aboutStatic.statement,
    paragraphs: [...aboutStatic.paragraphs],
    prefer: [...aboutStatic.prefer],
    stack: [...aboutStatic.stack],
    remote: aboutStatic.remote,
    imageSrc: "/v2/about-bust.png",
    caption: "based in Karachi, shipping worldwide",
    badge: "Open to new opportunities",
  },
  contact: {
    tagline: "08 / Contact",
    dim: "Have a product",
    bright: "worth",
    brightAccent: "building?",
    lead: "Let's talk about what you're building, what isn't working, and where I can help.",
    aside: { ...contactAside, items: [...contactAside.items] },
    projectTypes: [...projectTypes],
  },
  cta: {
    titleLine1: "Stop shipping templates.",
    titleAccent: "Start engineering products.",
    lead: "One engineer covers the whole frontend: React, Next.js, React Native and whatever comes next. Ship at your pace, with someone who owns the result alongside you.",
    buttonLabel: "Let's work together",
    buttonHref: "#contact",
    note: "Reply within 24 hours. Prefer a file?",
    socialText: "7+ years · 4 teams · 30+ products shipped",
    avatars: ["/v2/avatars/a1.jpg", "/v2/avatars/a2.jpg", "/v2/avatars/a3.jpg", "/v2/avatars/a4.jpg"],
  },
};

export const LANDING_SETTING_KEY = "landing";
